products/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login' ));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout' ));
Route::resource('product', 'ProductController'); 
Route::resource('user', 'UserController'); 

Route::get('/', function()
{
	$products = Product::all();
	return View::make('product.index', compact('products'));
	
});

products/app/models/Product.php
<?php 

class Product extends Eloquent{
    
    public static $rules = array(
            'name' => 'required|min:3',
            'price' => 'required'
    );
    
    
    
}

products/app/controllers/ProductController.php
<?php

class ProductController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$products = Product::all();
		return View::make('product.index')->with('products', $products); 
		//
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	 
	public function store()
	{	
		if (!Auth::check()) return Redirect::route('product.index');
		
		$input = Input::all();
		
		$product = Product::all();
		$product->name = $input['name'];
		$product->price = $input['price'];
		$product->save();
		return Redirect::route('product.show', $product->id);
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	 
	public function show($id)
	{
		
		$product = Product::find($id); 
		
		return View::make('product.show')->with('product', $product);
		
		// foreach ($products as $product)
		// var_dump($product->name);
		// exit();
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$product = Product::find($id); 
		
		return View::make('product.edit')->with('product', $product);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		if (!Auth::check()) return Redirect::route('product.index');
		
		$input = Input::all();
		
		$v = Validator::make($input, Product::$rules);
		
		if ($v->passes()){
			
			$product = Product::find($id);
			$product->name = $input['name'];
			$product->price = $input['price'];
			$product->save();
			return Redirect::route('product.show', $product->id);
			
		} else{
			// Show validation errors
		
			return Redirect::action('ProductController@edit', $id)->withErrors($v);
		}
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

products/app/views/product/edit.blade.php
@extends('product.layout')

@section('content')
<h1>Edit {{$product->name}}</h1>

{{Form::model( $product, array('method' => 'PUT', 'route' => array('product.update', $product['id']))) }}

{{ Form::label('name', 'Product Name: ') }}
{{ Form::text('name' ) }} 
{{ $errors->first('name') }}
<p></p>
{{ Form::label('price', 'Price: $') }}
{{ Form::text('price') }}
{{ $errors->first('price') }}
<p></p>

{{ Form::submit('Edit') }}

{{ Form::close() }}

@stop

products/app/views/product/index.blade.php
@extends('product.layout')

@section('content')
<h1>Products Home</h1>
@foreach ($products as $product)

<P>
    {{ link_to_route('product.show', $product->name, array($product->id)) }} <br>
    Price: ${{{ $product->price }}}
</P>



@endforeach

@stop

products/app/views/product/layout.blade.php
<html>
    <head>
        
    </head>
    
    <body>
        @if (Auth::check())
        
            {{ Auth::user()->username }} {{ link_to_route('user.logout', "(Sign out)" ) }}
            
        @else
        
            {{ Form::open(array('url' => secure_url('user/login'))) }}
                {{ Form::label('usernameLogin', 'Username: ') }}
                {{ Form::text('usernameLogin') }}
                {{ $errors->first('usernameLogin') }}
                
                {{ Form::label('passwordLogin', 'Password: ') }}
                {{ Form::text('passwordLogin') }}
                {{ $errors->first('passwordLogin') }}
                
                {{ Form::submit('Sign in') }}
            {{ Form::close() }}
            
            <p>If you don't have an account then {{ link_to_route('user.create', "Create an account" ) }}</p>
        @endif
        
        @section('content')
           
            
        @show
       
    </body>
</html>

products/app/views/product/show.blade.php
@extends('product.layout')



@section('content')
<h1>Product Details</h1>

<p>Name: {{{$product->name}}}</p> 
<p>Price: ${{{$product->price}}}</p>
<p>{{link_to_route('product.edit', 'Edit', array($product->id)) }}</p>


@stop