2503ict-assign2/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::get('user/userpage', array('as' => 'user.userpage', 'uses' => 'UserController@userpage'));
Route::get('user/loginpage', array('as' => 'user.loginpage', 'uses' => 'UserController@loginpage'));
// Route::post('user/loginpage', array('as' => 'user.loginpage', 'uses' => 'UserController@loginpage'));


Route::get('message/show_comment', array('as' => 'message.show_comment', 'uses' => 'MessageController@show_comment'));

Route::get('user/documentation', array('as' => 'user.documentation', 'uses' => 'UserController@documentation'));
Route::get('user/home_page', array('as' => 'user.home_page', 'uses' => 'UserController@home_page'));
Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login' ));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout' ));
Route::resource('message', 'MessageController');
Route::resource('comment', 'CommentController'); 
Route::resource('user', 'UserController'); 


Route::get('/', function()
{   
    $msgs = Message::all();
	  return View::make('social.input')->withMsgs($msgs);;

});

/*
// gets the IDs
Route::get('social.input/{id}', function ($id)
{
  $msg = get_msg($id);
	return View::make('social.input')->withMsg($msg);
}); 

// selects all of the colomns from the table called msg in the database (posts)
function get_msgs()
{
  $sql = "select * from msg";
  $msgs = DB::select($sql);
  return $msgs;
};

// selects the info from a row from the msg table in the database where the specified ID matches
function get_msg($id)
{
	$sql = "select id, title, name, message, post_date, img_path from msg where id = ?";
	$msgs = DB::select($sql, array($id));
    
	// If we get more than one item or no items display an error
	if (count($msgs) != 1) 
	{
    die("Invalid query or result: $query\n");
  }

	// Extract the first item (which should be the only item)
  $msg = $msgs[0];
	return $msg;
};

// gets info from the textfields and parses them to a function
Route::post('add_post_action', function()
{
  $title = Input::get('title');
  $name = Input::get('name');
  $message = Input::get('message');
  $date = date("d/m/y g:i a");
  $imgPath = "images/batman.jpg";

  $msga = add_msg($title, $name, $message, $date, $imgPath);

  // If successfully created then display newly created item
  if ($msga) 
  {
     $msgs = get_msgs();
    return View::make('social.input')->withMsgs($msgs);
  } 
  else
    die("Error adding item");
  });

// adds another post into the msg table in the database
function add_msg($title, $name, $message, $date, $imgPath) 
{
  $sql = "insert into msg (title, name, message, post_date, img_path) values (?, ?, ?, ?, ?)";

  DB::insert($sql, array($title, $name, $message, $date, $imgPath));

  $id = DB::getPdo()->lastInsertId();

  return $id;
};


// deletes a post with the specified ID
Route::get('delete_msg_action/{id}', function($id)
{
  $del = delete_msg($id);

  if ($del) 
  {
    $msgs = get_msgs();
    return View::make('social.input')->withMsgs($msgs);
   
  } 
  
});

// deletes the specified post from the database
function delete_msg($id)
{
 $sql = "delete from msg where id = ?";
 DB::delete($sql, array($id));

 return $sql;
};

// updates the home page
Route::get('update_msg/{id}', function($id)
{
  $msg = get_msg($id);
  return View::make('social.update')->withMsg($msg);
});

// Gets the information to update/edits the post
Route::post('update_msg_action', function()
{
  $title = Input::get('title');
  $name = Input::get('name');
  $message = Input::get('message');
  $date = date("d/m/y g:i a");
  $id = Input::get('id');
  $up = update_msg($title, $name, $message, $date, $id);

  // If successfully updated then display updated item
  if ($up) 
  {
      
      $msgs = get_msgs();
    return View::make('social.input')->withMsgs($msgs);
    
  } 
  
});

// updates the information of a post in the database
function update_msg($title, $name, $message, $date, $id)
{
 $sql = "update msg set title = ?, name = ?, message = ?, post_date = ?  where id = ?";
 DB::update($sql, array($title, $name, $message, $date, $id));
 
 return $sql;
};

// specifically made for the cancel button in the update page that goes back to the home page without updating the post
Route::get('go_back', function()
{
    $msgs = get_msgs();
    return View::make('social.input')->withMsgs($msgs);
});

// creates the comments page
Route::get('view_comments', function()
  {
    //$msgs = get_msg($id);
    $coms = get_coms();
    return View::make('social.comments')->withComs($coms);
  });
  
// gets the comments stored within the database
function get_coms()
{
  $sql = "select * from com";
  $coms = DB::select($sql);
  return $coms;
};
*/

// made for the Post button in the navigation bar to go to the home page
Route::get('home_page', function()
{   
    $msgs = DB::table('messages')->get();
		return View::make('social.input')->withMsgs($msgs);

});

// makes the documentation page
Route::get('documentation', function()
  {
    return View::make('social.documentation');
  });

2503ict-assign2/app/views/social/comments.blade.php
@extends('layouts.master')

@section('main_page')
<li>{{link_to_route('user.home_page', 'Posts')}}</li>
<li><a id = "home" href="{{{url("documentation")}}}" >Documentation</a></li>
<li><a id = "home" href="{{{url("friends")}}}" >Friends</a></li>
@if (Auth::check())
        
   <li>{{ link_to_route('user.edit', Auth::user()->email) }}</li> <li> {{ link_to_route('user.logout', "(Sign out)" ) }}</li>
            
@else

    <li>{{ link_to_route('user.loginpage', 'Login') }}</li>
    
@endif
@stop

@section('post')

            
            {{ Form::open(array('action' => 'CommentController@store', 'class' => 'post')) }}
                {{ Form::label('comment', 'Comment ') }}
                {{ Form::textarea('comment', null, array('class' => 'textarea', 'size' => '25x4')) }}
                {{ $errors->first('comment') }}
                <p></p>
                
                {{ Form::submit('Add Comment', ['id' => 'submit']) }}
            {{ Form::close() }}


@stop

@section('content')
<h1>Comments</h1>

@foreach($coms as $com)

<div class='post'>
                {{ Form::hidden('id', $com->id) }}
              <img href='{{{ url("social.input") }}}' class='photo' src='{{{ $com->img_path }}}' alt='Batman'>
               Date: {{{ $com->created_at  }}}  <br>
              <p>Comment:  {{{ $com->comment }}} </p> <br>
               {{ Form::open(array('method' => 'DELETE', 'route' => array('comment.destroy', $com->id))) }}
              {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
              {{ Form::close() }}
</div>

@endforeach

@stop

2503ict-assign2/app/views/social/documentation.blade.php
@extends('layouts.master')

@section('main_page')
<li>{{link_to_route('user.home_page', 'Posts')}}</li>
<li><a id = "home" href="{{{url("documentation")}}}" >Documentation</a></li>
<li><a id = "home" href="{{{url("friends")}}}" >Friends</a></li>
@if (Auth::check())
        
   <li>{{ link_to_route('user.edit', Auth::user()->email) }}</li> <li> {{ link_to_route('user.logout', "(Sign out)" ) }}</li>
            
@else

    <li>{{ link_to_route('user.loginpage', 'Login') }}</li>
    
@endif
@stop

@section('post')
<h1>Diagrams</h1>
<a href="images/db.png"><img src="images/db.png" alt="ER diagram of database" height="200" width="200"></img></a> <br>
<a href="images/site.png"><img src="images/site.png" alt="site diagram" height="200" width="200"></img></a>
@stop

@section('content')
<h1>Documentation</h1>
<p id="doc">For the 2nd assignment I was able to complete some tasks. I was ablt to complete task 1
even though my 1st assignment was finished i still managed to get all of what was needed in the 1st assignment 
and had it in this assignment. As for task 2 i was only able to complete some of it like adding user functionality
where you can create an account and login. Also to be able to create and posts or comments you have to be logged in.
I have also implemented validation for the textfield thoughout the site.
I have also pre seeded the databases. As for friends i have not implemented anything for it or any image handling 
as stapler broke my assignment when i installed it so i decided to to risk it again. There is no pagination either.</p>
@stop

2503ict-assign2/app/views/social/input.blade.php
@extends('layouts.master')

@section('main_page')
<li>{{link_to_route('user.home_page', 'Posts')}}</li>
<li><a id = "home" href="{{{url("documentation")}}}" >Documentation</a></li>
<li><a id = "home" href="{{{url("friends")}}}" >Friends</a></li>

@if (Auth::check())
        
   <li>{{ link_to_route('user.edit', Auth::user()->email) }}</li> <li> {{ link_to_route('user.logout', "(Sign out)" ) }}</li>
            
@else

    <li>{{ link_to_route('user.loginpage', 'Login') }}</li>
    
@endif

@stop


@section('post')

@if (Auth::check())
        
    {{ Form::open(array('action' => 'MessageController@store', 'class' => 'post')) }}
                {{ Form::hidden('id', Auth::user()->id) }}
                {{ Form::label('title', 'Title: ') }}
                </br>
                {{ Form::text('title', null, array('class' => 'textarea')) }}
                {{ $errors->first('title') }}
                <p></p>
                
                {{ Form::label('message', 'Message: ') }}
                {{ Form::textarea('message', '', array('class' => 'textarea', 'size' => '25x4') ) }}
                {{ $errors->first('message') }}
                
                <p></p>
                {{ Form::submit('Add Message', ['id' => 'submit']) }}
            {{ Form::close() }}
    
@endif
        
           


@stop



@section('content')

@foreach ($msgs as $msg)

<div class='post'>
                {{ Form::hidden('id', $msg->id)}}
                
              <img href='{{{ url("social.input") }}}' class='photo' src='{{{ $msg->img_path }}}' alt='Batman'>
              Title: {{{ $msg->m_name }}}<br>
               Date: {{{ $msg->created_at }}}  <br>
              <p>Message:  {{{ $msg->message }}} </p>
              {{ Form::open(array('method' => 'DELETE', 'route' => array('message.destroy', $msg->id))) }}
              {{ Form::submit('Delete', array('id' => 'submit')) }}
              {{ Form::close() }}
              
              {{ Form::open(array('action' => 'CommentController@index')) }}
                  {{ Form::submit('Comments', ['id' => 'submit']) }}
              {{ Form::close() }}
              
              <button id="submit">{{ link_to_route('message.edit', 'Update', $msg->id) }}</button>
              
              
              
             
             
</div>

@endforeach

@stop

2503ict-assign2/app/views/social/login.blade.php
@extends('layouts.master')

@section('main_page')
<li>{{link_to_route('user.home_page', 'Posts')}}</li>
<li><a id = "home" href="{{{url("documentation")}}}" >Documentation</a></li>
<li><a id = "home" href="{{{url("friends")}}}" >Friends</a></li>
@if (Auth::check())
        
   <li>{{ link_to_route('user.edit', Auth::user()->email, Auth::user()->id) }}</li> <li> {{ link_to_route('user.logout', "(Sign out)" ) }}</li>
            
@else

    <li>{{ link_to_route('user.loginpage', 'Login') }}</li>
    
@endif
@stop

@section('post')
<h1>Login</h1>
            
        
            
            
        
            {{ Form::open(array('url' => secure_url('user/login'), 'class' => 'post')) }}
                {{ Form::label('emailLogin', 'Email: ') }}
                {{ Form::email('emailLogin', null, ['class' => 'textarea']) }}
                {{ $errors->first('emailLogin') }}
                <p></p>
                {{ Form::label('passwordLogin', 'Password: ') }}
                {{ Form::password('passwordLogin', ['class' => 'textarea']) }}
                {{ $errors->first('passwordLogin') }}
                <p></p>
                {{ Form::submit('Sign in', ['id' => 'submit']) }}
            {{ Form::close() }}
            
    

@stop

@section('content')

<h1>Create Account</h1>

{{ Form::open(array('url' => secure_url('user'), 'files' => 'true', 'class' => 'post')) }}
    {{ Form::label('email', 'email: ') }}
    {{ Form::email('email', null, ['class' => 'textarea']) }}
    {{ $errors->first('email') }}
    <p></p>
    {{ Form::label('fullname', 'Full Name: ') }}
    {{ Form::text('fullname', null, ['class' => 'textarea']) }}
    {{ $errors->first('fullname') }}
    <p></p>
    {{ Form::label('dob', 'Date of birth: ') }}
    {{ Form::input('date', 'dob', null, ['class' => 'textarea']) }}
    {{ $errors->first('dob') }}
    <p></p>
    {{ Form::label('passwordcreate', 'Password: ') }}
    {{ Form::password('password', null, ['class' => 'textarea']) }}
    {{ $errors->first('password') }}
    <p></p>
    {{ Form::label('dp', 'Profile Picture: ') }}
    {{ Form::file('dp') }}
    {{ $errors->first('dob') }}
    <p></p>
    {{ Form::submit('Create', ['id' => 'submit']) }}
{{ Form::close() }}

@stop

2503ict-assign2/app/views/social/update.blade.php
@extends('layouts.master')

@section('main_page')
<li>{{link_to_route('user.home_page', 'Posts')}}</li>
<li><a id = "home" href="{{{url("documentation")}}}" >Documentation</a></li>
<li><a id = "home" href="{{{url("friends")}}}" >Friends</a></li>
@if (Auth::check())
        
   <li>{{ link_to_route('user.edit', Auth::user()->email) }}</li> <li> {{ link_to_route('user.logout', "(Sign out)" ) }}</li>
            
@else

    <li>{{ link_to_route('user.loginpage', 'Login') }}</li>
    
@endif
@stop

@section('post')
<h1>Update Message</h1>

{{Form::model( $messages, ['method' => 'put', 'route' => array( 'message.update', $messages['id'])] ) }}

{{ Form::label('message', 'Message: ') }}
{{ Form::textarea('message', $messages['message'], array('class' => 'textarea') ) }}
{{ $errors->first('message') }}
<p></p>

{{ Form::submit('Update') }}

{{ Form::close() }}

@stop

@section('content')

{{ link_to_route('user.home_page', 'Cancel') }}

@stop

2503ict-assign2/app/views/social/user.blade.php
@extends('layouts.master')

@section('main_page')

<li>{{link_to_route('user.home_page', 'Posts')}}</li>
<li><a id = "home" href="{{{url("documentation")}}}" >Documentation</a></li>
<li><a id = "home" href="{{{url("friends")}}}" >Friends</a></li>

@if (Auth::check())
        
   <li>{{ link_to_route('user.edit', Auth::user()->email) }}</li> <li> {{ link_to_route('user.logout', "(Sign out)" ) }}</li>
            
@else

    <li>{{ link_to_route('user.loginpage', 'Login') }}</li>
    
@endif

@stop

@section('post')
<h1>Welcome {{Auth::user()->fullname}}</h1>
<img src="{{ Auth::user()->profile_image }}"></img>
<p>Date of Birth: {{Auth::user()->date_of_birth}}</p>
@stop

@section('content')
<h1>Edit Details</h1>
{{Form::model(['method' => 'PUT', 'route' => array( 'user.update', Auth::user()->id )] ) }}
    {{ Form::label('fullname', 'Full Name: ') }}
    {{ Form::text('fullname', Auth::user()->fullname, ['class' => 'textarea']) }}
    {{ $errors->first('fullname') }}
    <p></p>
    {{ Form::label('dob', 'Date of birth: ') }}
    {{ Form::input('date', 'dob', Auth::user()->date_of_birth, ['class' => 'textarea']) }}
    {{ $errors->first('dob') }}
    <p></p>
    {{ Form::label('passwordcreate', 'Password: ') }}
    {{ Form::password('password', null, ['class' => 'textarea']) }}
    {{ $errors->first('password') }}
    <p></p>
    {{ Form::label('dp', 'Profile Picture: ') }}
    {{ Form::file('dp') }}
    {{ $errors->first('dob') }}
    <p></p>
    {{ Form::submit('Update', ['id' => 'submit']) }}
{{ Form::close() }}

@stop